# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-13 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tannersapp', '0002_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tannersapp.Band'),
        ),
    ]
